local LSM = LibStub('LibSharedMedia-3.0')

if LSM == nil then return end

LSM:Register('font','LizeUI Medium', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\AvantGardeLT-Medium.ttf]])
LSM:Register('font','LizeUI Bold', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\AvantGardeLT-Bold.ttf]])
LSM:Register('font','LizeUI Demi', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\AvantGardeLT-Demi.ttf]])
LSM:Register('font','LizeUI Numbers', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\AvantGardeLT-Numbers.ttf]])
LSM:Register('font','Bui Prototype', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\PROTOTYPE.TTF]])
LSM:Register('font','Bui PrototypeRU', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\PROTOTYPE_RU.TTF]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font','Bui Visitor1', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\visitor1.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font','Bui Visitor2', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\visitor2.ttf]])
LSM:Register('font','Bui Tukui', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\uf_font.ttf]], LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_western)
LSM:Register('font','Bui Kait', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\heavy_dock_kait.ttf]])
LSM:Register('font','Bui ArialN', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\ARIALN.ttf]])
LSM:Register('font','Bui Homizio', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\homizio_bold.ttf]])
LSM:Register('font','Bui FiraBold', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\FiraSansCondensed-Bold.ttf]])
LSM:Register('font','JetBrainsMono Medium', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\JetBrainsMono-Medium.ttf]])
LSM:Register('font','JetBrainsMono Regular', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\JetBrainsMono-Regular.ttf]])
LSM:Register('font','JetBrains SemiBold', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\JetBrainsMono-SemiBold.ttf]])
LSM:Register('font','JetBrainsMono-Bold', [[Interface\AddOns\ElvUI_LizeUI\media\fonts\JetBrainsMono-Bold.ttf]])

LSM:Register('statusbar','AsphyxiaNorm', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\AsphyxiaNorm.tga]])
LSM:Register('statusbar','BuiOnePixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\BuiOnePixel.tga]])
LSM:Register('statusbar','Dragonflight01', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Dragonflight01.tga]])
LSM:Register('statusbar','Dragonflight02', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Dragonflight02.tga]])
LSM:Register('statusbar','Dragonflight03', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Dragonflight03.tga]])
LSM:Register('statusbar','Eltreum-20pc', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-20pc.tga]])
LSM:Register('statusbar','Eltreum-30pc', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-30pc.tga]])
LSM:Register('statusbar','Eltreum-Blank', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Blank.tga]])
LSM:Register('statusbar','Eltreum-bottom', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-bottom.tga]])
LSM:Register('statusbar','Eltreum-Dark', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Dark.tga]])
LSM:Register('statusbar','Eltreum-DH', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-DH.tga]])
LSM:Register('statusbar','Eltreum-DHv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-DHv2.tga]])
LSM:Register('statusbar','Eltreum-DHv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-DHv3.tga]])
LSM:Register('statusbar','Eltreum-Diagonal', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Diagonal.tga]])
LSM:Register('statusbar','Eltreum-DK', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-DK.tga]])
LSM:Register('statusbar','Eltreum-DKv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-DKv2.tga]])
LSM:Register('statusbar','Eltreum-DKv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-DKv3.tga]])
LSM:Register('statusbar','Eltreum-DR', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-DR.tga]])
LSM:Register('statusbar','Eltreum-DRv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-DRv2.tga]])
LSM:Register('statusbar','Eltreum-DRv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-DRv3.tga]])
LSM:Register('statusbar','Eltreum-Elvui-Norm', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Elvui-Norm.tga]])
LSM:Register('statusbar','Eltreum-EV', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-EV.tga]])
LSM:Register('statusbar','Eltreum-EVv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-EVv2.tga]])
LSM:Register('statusbar','Eltreum-EVv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-EVv3.tga]])
LSM:Register('statusbar','Eltreum-HT', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-HT.tga]])
LSM:Register('statusbar','Eltreum-HTv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-HTv2.tga]])
LSM:Register('statusbar','Eltreum-HTv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-HTv3.tga]])
LSM:Register('statusbar','Eltreum-left', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-left.tga]])
LSM:Register('statusbar','Eltreum-MG', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-MG.tga]])
LSM:Register('statusbar','Eltreum-MGv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-MGv2.tga]])
LSM:Register('statusbar','Eltreum-MGv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-MGv3.tga]])
LSM:Register('statusbar','Eltreum-MK', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-MK.tga]])
LSM:Register('statusbar','Eltreum-MKv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-MKv2.tga]])
LSM:Register('statusbar','Eltreum-MKv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-MKv3.tga]])
LSM:Register('statusbar','Eltreum-PL', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-PL.tga]])
LSM:Register('statusbar','Eltreum-PLv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-PLv2.tga]])
LSM:Register('statusbar','Eltreum-PLv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-PLv3.tga]])
LSM:Register('statusbar','Eltreum-PR', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-PR.tga]])
LSM:Register('statusbar','Eltreum-PRv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-PRv2.tga]])
LSM:Register('statusbar','Eltreum-PRv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-PRv3.tga]])
LSM:Register('statusbar','Eltreum-RG', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-RG.tga]])
LSM:Register('statusbar','Eltreum-RGv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-RGv2.tga]])
LSM:Register('statusbar','Eltreum-RGv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-RGv3.tga]])
LSM:Register('statusbar','Eltreum-right', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-right.tga]])
LSM:Register('statusbar','Eltreum-SH', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-SH.tga]])
LSM:Register('statusbar','Eltreum-SHv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-SHv2.tga]])
LSM:Register('statusbar','Eltreum-SHv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-SHv3.tga]])
LSM:Register('statusbar','Eltreum-Stripes', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Stripes.tga]])
LSM:Register('statusbar','Eltreum-Stripes2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Stripes2.tga]])
LSM:Register('statusbar','Eltreum-Stripes3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Stripes3.tga]])
LSM:Register('statusbar','Eltreum-Stripes4', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Stripes4.tga]])
LSM:Register('statusbar','Eltreum-Tapped', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Tapped.tga]])
LSM:Register('statusbar','Eltreum-Tappedv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Tappedv2.tga]])
LSM:Register('statusbar','Eltreum-Tappedv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Tappedv3.tga]])
LSM:Register('statusbar','Eltreum-top', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-top.tga]])
LSM:Register('statusbar','Eltreum-Transparent', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-Transparent.tga]])
LSM:Register('statusbar','Eltreum-WA', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-WA.tga]])
LSM:Register('statusbar','Eltreum-WAv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-WAv2.tga]])
LSM:Register('statusbar','Eltreum-WAv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-WAv3.tga]])
LSM:Register('statusbar','Eltreum-WL', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-WL.tga]])
LSM:Register('statusbar','Eltreum-WLv2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-WLv2.tga]])
LSM:Register('statusbar','Eltreum-WLv3', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum-WLv3.tga]])
LSM:Register('statusbar','Eltreum10pixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum10pixel.tga]])
LSM:Register('statusbar','Eltreum1pixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum1pixel.tga]])
LSM:Register('statusbar','Eltreum2pixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum2pixel.tga]])
LSM:Register('statusbar','Eltreum3pixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum3pixel.tga]])
LSM:Register('statusbar','Eltreum4pixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum4pixel.tga]])
LSM:Register('statusbar','Eltreum5pixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum5pixel.tga]])
LSM:Register('statusbar','Eltreum6pixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum6pixel.tga]])
LSM:Register('statusbar','Eltreum7pixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum7pixel.tga]])
LSM:Register('statusbar','Eltreum7pixelB', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum7pixelB.tga]])
LSM:Register('statusbar','Eltreum8pixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum8pixel.tga]])
LSM:Register('statusbar','Eltreum9pixel', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Eltreum9pixel.tga]])
LSM:Register('statusbar','EltreumFade', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\EltreumFade.tga]])
LSM:Register('statusbar','Empty', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Empty.tga]])
LSM:Register('statusbar','Flat', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Flat.tga]])
LSM:Register('statusbar','Kait1', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Kait1.tga]])
LSM:Register('statusbar','Kait2', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Kait2.tga]])
LSM:Register('statusbar','KMT32', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\KMT32.tga]])
LSM:Register('statusbar','Melli', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\Melli.tga]])
LSM:Register('statusbar','MelliDark', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\MelliDark.tga]])
LSM:Register('statusbar','None', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\None.tga]])
LSM:Register('statusbar','pHishTex29', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\pHishTex29.tga]])
LSM:Register('statusbar','pHishTex35', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\pHishTex35.tga]])
LSM:Register('statusbar','pHishTex5', [[Interface\AddOns\ElvUI_LizeUI\media\textures\statusbar\pHishTex5.tga]])
