_G.LizeUI_ImportStrings = _G.LizeUI_ImportStrings or {}

-- Luxthos - Druid: Guardian (Cooldown Manager)
_G.LizeUI_ImportStrings.druid_guardian_luxthos = "1|NdE9SwNBEAbg3U0wm7s0AYu8g8UJomksU2hjIx7Y+hXxgwukiYJoINiJuWiTxN5GJIWof0IstLK3scinySXnT7DQuUua5x2YvR127ip62UidNSKV23Vk35F9IyHjCtojIWM+dIuEVL8waqhmYNQRT5JQax8kpHPEHJNQqT7jMUNmRELqJIwFGMvQHeg2dB/nc9Bd6B4u+MMYH4oNoZucHnQUekRCbSzxDT8wbqB9WCswBjxmk1suEg4SdzAdmDYJZU9za4vZYbLMLrPH7DMHzCEJWXhhXknIL+IRTabFtJkO02V6zDczYHwSCmkSij5JqJlH5omEmucj6Xu+fvtBuMG6gtVId/IC5QZdGAOrHKxk9hqmjYQTPsbkxzxDt8oVJaegvTDjyTCN2jjrYVYzQQb/Y1LF/HH1PzeoGpHT1WKpkLcWLbuUK+YLuZM/"
